const s1 = "danger";
const s2 = "garden";

const anagrams = (s1, s2) => {
  if (s1.length !== s2.length) {
    return false;
  }
  
  let s1Map = {};
  let s2Map = {};

  const reducer = (sMap, sChar) => {
    if (sMap[sChar]) {
      sMap[sChar]++;
    } else {
      sMap[sChar] = 1;
    }
    return sMap;
  }

  s1Map = s1.split('').reduce(reducer, {});
  s2Map = s2.split('').reduce(reducer, {});

  if (Object.keys(s1Map).length !== Object.keys(s2Map).length) {
    return false;
  }

  for (let key in s1Map) {
    if (!s2Map[key] || s1Map[key] !== s2Map[key]) {
      return false;
    }
  }

  return true;
}

// This code was generated by Github Copilot
// const anagrams = (s1, s2) => {
//   if (s1.length !== s2.length) {
//     return false;
//   }
//   const s1Map = {};
//   const s2Map = {};
//   for (let i = 0; i < s1.length; i++) {
//     const char = s1[i];
//     if (s1Map[char]) {
//       s1Map[char]++;
//     } else {
//       s1Map[char] = 1;
//     }
//   }
//   for (let i = 0; i < s2.length; i++) {
//     const char = s2[i];
//     if (s2Map[char]) {
//       s2Map[char]++;
//     } else {
//       s2Map[char] = 1;
//     }
//   }
//   for (let char in s1Map) {
//     if (s1Map[char] !== s2Map[char]) {
//       return false;
//     }
//   }
//   return true;
// }

// This code was also generated by Github Copilot
// const anagrams = (s1, s2) => {
//   if (s1.length !== s2.length) {
//     return false;
//   }
//   const s1Letters = {};
//   const s2Letters = {};
//   for (let i = 0; i < s1.length; i++) {
//     const letter = s1[i];
//     if (s1Letters[letter]) {
//       s1Letters[letter]++;
//     } else {
//       s1Letters[letter] = 1;
//     }
//   }
//   for (let i = 0; i < s2.length; i++) {
//     const letter = s2[i];
//     if (s2Letters[letter]) {
//       s2Letters[letter]++;
//     } else {
//       s2Letters[letter] = 1;
//     }
//   }
//   for (let letter in s1Letters) {
//     if (!s2Letters[letter] || s1Letters[letter] !== s2Letters[letter]) {
//       return false;
//     }
//   }
//   return true;
// }

console.log(anagrams(s1, s2));
