const arr = [4,2,9,7,5,6,7,1,3];
k = 4;
// output = 6

// TODO: Test borders, what happens if k > arr.length
const findKthLargestElement = (arr, k) => {
  const auxArray = arr;
  let max = 0;

  for (let i = k; i > 0; i--) {
    max = Math.max(...auxArray);
    auxArray.splice(auxArray.indexOf(max), 1);
  }
  return max;
}

// Generated by Github Copilot
// const findKthLargestElement = (arr, k) => {
//   const kthLargestElement = arr.sort((a, b) => b - a)[k - 1];
//   return kthLargestElement;
// }

console.log(findKthLargestElement(arr, k));

